# Standards: 0.1
---
- name: Fact screesaver user
  set_fact:
    screensaver_user: '{{ screensaver_user | default(homebrew_user) | default(ansible_user_id) }}'
  tags:
    - screensaver

- become: '{{ (screensaver_user != ansible_user_id) | bool }}'
  become_user: '{{ screensaver_user }}'
  block:
    - name: Define idle time
      osx_defaults:
        domain: com.apple.screensaver
        key: idleTime
        host: currentHost
        type: int
        value: '{{ screensaver_idle_time }}'
        state: present
      tags:
        - screensaver

    - name: Show clock screen
      osx_defaults:
        domain: com.apple.screensaver
        key: showClock
        host: currentHost
        type: bool
        value: '{{ screensaver_show_clock }}'
        state: present
      tags:
        - screensaver

    - name: Ask for password
      osx_defaults:
        domain: com.apple.screensaver
        key: askForPassword
        type: bool
        value: '{{ screensaver_ask_for_password }}'
        state: present
      tags:
        - screensaver

    - name: Ask password delay
      osx_defaults:
        domain: com.apple.screensaver
        key: askForPasswordDelay
        type: int
        value: '{{ screensaver_password_delay }}'
        state: present
      tags:
        - screensaver

...
